'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ayuda.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;html&gt;
        '''	
        '''&lt;head&gt;
        '''	&lt;title&gt;Archivo&lt;/title&gt;
        '''	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;generator&quot; content=&quot;HelpNDoc Personal Edition 4.6.2.573&quot;&gt;
        '''	&lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        '''	
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/reset.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/base.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/hnd.css&quot; /&gt;
        '''	&lt;!--[if lte IE 8]&gt;
        '''		&lt;link type=&quot;text/css&quot; rel=&quot;styles [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Archivo() As String
            Get
                Return ResourceManager.GetString("Archivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Archivo_de_ayuda() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Archivo_de_ayuda", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Frameset//EN&quot; &quot;http://www.w3.org/TR/html4/frameset.dtd&quot;&gt;
        '''&lt;html&gt;
        '''
        '''&lt;head&gt;
        '''
        '''	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;generator&quot; content=&quot;HelpNDoc Personal Edition 4.6.2.573&quot;&gt;
        '''    &lt;title&gt;Archivo de ayuda&lt;/title&gt;
        '''    &lt;script type=&quot;text/javascript&quot;&gt;
        '''      function escapeHtml(unsafe) {
        '''        return unsafe.replace(/&amp;/g, &quot;&amp;amp;&quot;).replace(/&lt;/g, &quot;&amp;lt;&quot;).replace(/&gt;/g, &quot;&amp;gt;&quot;).replace(/&quot;/g, &quot;&amp;quot;&quot;).replace(/&apos;/g, &quot;&amp;#039 [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Archivo_de_ayuda1() As String
            Get
                Return ResourceManager.GetString("Archivo_de_ayuda1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;html&gt;
        '''	
        '''&lt;head&gt;
        '''	&lt;title&gt;Bienvenido&lt;/title&gt;
        '''	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;generator&quot; content=&quot;HelpNDoc Personal Edition 4.6.2.573&quot;&gt;
        '''	&lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        '''	
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/reset.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/base.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/hnd.css&quot; /&gt;
        '''	&lt;!--[if lte IE 8]&gt;
        '''		&lt;link type=&quot;text/css&quot; rel=&quot;sty [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Bienvenido() As String
            Get
                Return ResourceManager.GetString("Bienvenido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;html&gt;
        '''	
        '''&lt;head&gt;
        '''	&lt;title&gt;Capturas de pantalla&lt;/title&gt;
        '''	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;generator&quot; content=&quot;HelpNDoc Personal Edition 4.6.2.573&quot;&gt;
        '''	&lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        '''	
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/reset.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/base.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/hnd.css&quot; /&gt;
        '''	&lt;!--[if lte IE 8]&gt;
        '''		&lt;link type=&quot;text/css [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Capturasdepantalla() As String
            Get
                Return ResourceManager.GetString("Capturasdepantalla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;html&gt;
        '''	
        '''&lt;head&gt;
        '''	&lt;title&gt;Edici&amp;oacute;n&lt;/title&gt;
        '''	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;generator&quot; content=&quot;HelpNDoc Personal Edition 4.6.2.573&quot;&gt;
        '''	&lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        '''	
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/reset.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/base.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/hnd.css&quot; /&gt;
        '''	&lt;!--[if lte IE 8]&gt;
        '''		&lt;link type=&quot;text/css&quot; rel= [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Edicion() As String
            Get
                Return ResourceManager.GetString("Edicion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;html&gt;
        '''	
        '''&lt;head&gt;
        '''	&lt;title&gt;Herramientas&lt;/title&gt;
        '''	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;generator&quot; content=&quot;HelpNDoc Personal Edition 4.6.2.573&quot;&gt;
        '''	&lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        '''	
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/reset.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/base.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/hnd.css&quot; /&gt;
        '''	&lt;!--[if lte IE 8]&gt;
        '''		&lt;link type=&quot;text/css&quot; rel=&quot;s [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Herramientas() As String
            Get
                Return ResourceManager.GetString("Herramientas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;html&gt;
        '''	
        '''&lt;head&gt;
        '''	&lt;title&gt;Presentaci&amp;oacute;n&lt;/title&gt;
        '''	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;generator&quot; content=&quot;HelpNDoc Personal Edition 4.6.2.573&quot;&gt;
        '''	&lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        '''	
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/reset.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/base.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/hnd.css&quot; /&gt;
        '''	&lt;!--[if lte IE 8]&gt;
        '''		&lt;link type=&quot;text/css&quot; [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Presentacion() As String
            Get
                Return ResourceManager.GetString("Presentacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;html&gt;
        '''	
        '''&lt;head&gt;
        '''	&lt;title&gt;Referencia de funciones&lt;/title&gt;
        '''	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;generator&quot; content=&quot;HelpNDoc Personal Edition 4.6.2.573&quot;&gt;
        '''	&lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        '''	
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/reset.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/base.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/hnd.css&quot; /&gt;
        '''	&lt;!--[if lte IE 8]&gt;
        '''		&lt;link type=&quot;text/ [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Referenciadefunciones() As String
            Get
                Return ResourceManager.GetString("Referenciadefunciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;html&gt;
        '''	
        '''&lt;head&gt;
        '''	&lt;title&gt;Requisitos minimos&lt;/title&gt;
        '''	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;generator&quot; content=&quot;HelpNDoc Personal Edition 4.6.2.573&quot;&gt;
        '''	&lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        '''	
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/reset.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/base.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/hnd.css&quot; /&gt;
        '''	&lt;!--[if lte IE 8]&gt;
        '''		&lt;link type=&quot;text/css&quot;  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Requisitosminimos() As String
            Get
                Return ResourceManager.GetString("Requisitosminimos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        '''&lt;html&gt;
        '''
        '''&lt;head&gt;
        '''	&lt;title&gt;Archivo de ayuda- Table of Contents&lt;/title&gt;
        '''	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;generator&quot; content=&quot;HelpNDoc Personal Edition 4.6.2.573&quot;&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/reset.css&quot; /&gt;
        '''	&lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot; href=&quot;css/silver-theme/jquery-ui-1.8.12.custom.css&quot; /&gt;
        '''	&lt;link  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property toc() As String
            Get
                Return ResourceManager.GetString("toc", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
